\documentclass{article}
%\VignettePackage{adephylo}
% \VignetteIndexEntry{adephylo: exploratory analyses for the
% phylogenetic comparative method}
\usepackage{graphicx}
\usepackage[colorlinks=true,urlcolor=blue]{hyperref}
\usepackage{array}
\usepackage{color}

\usepackage[utf8]{inputenc} % for UTF-8/single quotes from sQuote()
\newcommand{\code}[1]{{{\tt #1}}}
\title{The \code{adephylo} package}
\author{Thibaut Jombart}
\date{\today}
\begin{document}
\maketitle
\tableofcontents



%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%
\section{Introduction}
%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%

\SweaveOpts{prefix.string = figs/adephylo, fig = FALSE, eps = FALSE, pdf = TRUE, width = 6, height = 6}

This document describes the \code{adephylo} package for the R software.
\code{adephylo} aims at implementing exploratory methods for the
analysis of phylogenetic comparative data, i.e. biological traits measured for
taxa whose phylogeny is also provided.
Procedures implemented in this package rely on exploratory data
analysis.
They include data visualization and manipulation, tests for phylogenetic
autocorrelation, multivariate analysis, computation of phylogenetic
proximities and distances, and modelling phylogenetic signal using
orthonormal bases.
\\

These methods can be used to visualize, test, remove or investigate
the phylogenetic signal in comparative data.
The purpose of this document is to provide a general view a the main
functionalities of \code{adephylo}, and to show how this package can be
used along with \code{ape}, \code{phylobase} and \code{ade4} to
analyse comparative data.






%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%
\section{First steps into \code{adephylo}}
%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%%%
\subsection{Data representation: why we are not reinventing the weel}
%%%%%%%%%%%%%%%%%%%%%
Data representation can be defined as the way data are stored in a
software (R, in our case).
Technically, they are classes of objects containing the information.
In the case of phylogeny, and comparative data, very efficient data
representation are already defined in other packages.
Hence, it made much more sense using directly objects from these classes.
\\


Phylogenies are best represented in Emmanuel Paradis's \code{ape}
package (\url{http://ape.mpl.ird.fr/}),
as the class \code{phylo}. Note that as \code{ape} is by far the
largest package dedicated to phylogeny, using the \code{phylo} class
assures a good interoperability of data. This class is defined in an
online document: \url{http://ape.mpl.ird.fr/misc/FormatTreeR_28July2008.pdf}.
\\

However, data that are to be analyzed in \code{adephylo} do not only
contain trees, but also traits associated to the tips of a tree.
The package \code{phylobase}
(\url{http://r-forge.r-project.org/projects/phylobase/}) is a
collaborative effort designed to the handling of such data.
Its representation of phylogenies is very similar to that of
\code{ape}: the class \code{phylo4} basically is an extension of
\code{phylo} class into formal (S4) class.
More interestingly, the S4 class \code{phylo4d} can be used to store a
tree and data associated to tips, internal nodes, or even edges of a tree.
Classes of \code{phylobase} are described in a vignette of the
package, accessible by typing:
<<eval=FALSE>>=
vignette("phylobase", package="phylobase")
@

~\\
As trees and comparative data are already handled by \code{ape} and
\code{phylobase}, no particular data format shall be defined in
\code{adephylo}.
In particular, we are no longer using \code{phylog} objects, which
were used to represent phylogenies in \code{ade4}.
This class is now deprecated, but all previous functionalities
available for \code{phylog} objects have been re-implemented and
-- in some cases -- improved in \code{adephylo}.





%%%%%%%%%%%%%%%%%%%%%
\subsection{Installing the package}
%%%%%%%%%%%%%%%%%%%%%
What is tricky here is that a vignette is basically available once the
package is installed.
Assuming you got this document before installing the package, here are
some clues about installing \code{adephylo}.
\\

First of all, \code{adephylo} depends on other packages, being
\code{methods}, \code{ape}, \code{phylobase}, and \code{ade4}.
These dependencies are mandatory, that is, you actually need to have
these packages installed (with or without their dependencies) before
using \code{adephylo}.
Also, it is better to make sure you are using the latest versions of
these packages. This can be achieved by typing
\texttt{update.packages}, or (better for \code{ade4} and \code{phylobase}) by installing devel versions
from R-Forge (\url{http://r-forge.r-project.org/}).
In all cases, the latest version of \code{adephylo} can be found from
\url{http://r-forge.r-project.org/R/?group_id=303}.
\\

When loading the package, dependencies are also loaded:
<<load>>=
library(adephylo)
@

Note that possibly conflicting, deprecated functions or datasets from \code{ade4} are
masked by \code{adephylo}.
In case the converse would occur (i.e. deprecated function masking a
function of \code{adephylo}), one can refer to the 'good' version of a
function by adding the prefix \code{adephylo::} to the function,
without space.
Hence, it is possibly to coerce the version of a masked function,
using a kludge like:
<<kludge>>=
cat("\\n=== Old - deprecated- version ===\\n")
orthogram <- ade4::orthogram
args(orthogram)
cat("\\n=== New version === \\n")
orthogram <- adephylo::orthogram
args(orthogram)
@

Luckily, this should not be required as long as one is not playing
with loading and unloading \code{ade4} once \code{adephylo} is loaded.


%%%%%%%%%%%%%%%%%%%%%
\subsection{Getting started}
%%%%%%%%%%%%%%%%%%%%%
All the material of the package is summarized in a manpage accessible
by typing:
<<eval=FALSE>>=
?adephylo
@

Note that a html version may be preferred to browse easily the content
of \code{adephylo}; this is accessible by typing:
<<eval=FALSE>>=
help("adephylo", package="adephylo", html=TRUE)
@

To revert help back to text mode, simply type:
<<eval=FALSE>>=
options(htmlhelp = FALSE)
@





%%%%%%%%%%%%%%%%%%%%%
\subsection{Putting data into shape}
%%%%%%%%%%%%%%%%%%%%%
While this is not the purpose of this document to go through the
details of \code{phylo}, \code{phylo4} and \code{phylo4d} objects, we
shall show briefly how these objects can be obtained.


% % % % % % % % % % %
\subsubsection{Making a \code{phylo} object}
% % % % % % % % % % %
The simplest way of turning a tree into a \code{phylo} object is using
ape's function \code{read.tree}.
This function reads a tree with the Newick (or 'parentetic') format,
from a file (default, argument \code{file}) of from a character string
(argument \code{text}).
<<readTree, plot=TRUE>>=
data(ungulates)
ungulates$tre
myTree <- read.tree(text=ungulates$tre)
myTree
plot(myTree, main="ape's plotting of a tree")
@


It is easy to convert \code{ade4}'s \code{phylog} objects to a
\code{phylo}, as \code{phylog} objects store the Newick format of the
tree in the \code{\$tre} component.
\\

Note that \code{phylo} trees can also be constructed from alignements
(see \code{read.GenBankdist.dna}, \code{read.dna},
\code{dist.dna}, \code{nj}, \code{bionj}, and \code{mlphylo}, all in
\code{ape}), or even simulated (for instance, see \code{rtree}).
\\

Also note that, if needed, conversion can be done back and forward
with \code{phylo4} trees:
<<>>=
temp <- as(myTree, "phylo4")
class(temp)
temp <- as(temp, "phylo")
class(temp)
all.equal(temp, myTree)
@





% % % % % % % % % % %
\subsubsection{Making a \code{phylo4d} object}
% % % % % % % % % % %
\code{phylo4d} objects are S4 objects, and are thus created in a
particular way.
The most immediate way of creating a \code{phylo4d} object is to call
to the constructor, also named \code{phylo4d}.
This is a function that takes two arguments: a tree (\code{phylo} or
\code{phylo4} format) and a data.frame containing data, for tips by
default (see \code{?phylo4d} for more information).
Here is an example:
<<phylo4d, fig=TRUE>>=
ung <- phylo4d(myTree, ungulates$tab)
class(ung)
table.phylo4d(ung)
@

\noindent Note that the constructor checks the consistency of the
names used for the tips of the tree and for the rows of the data.frame.
Inconsistencies issue an error.
To override this behaviour, one can specify
\code{use.tip.names=FALSE}.
However, this can be tricky: often, mismatches between names can
indicate that data are not sorted adequately; moreover, object created
with such mismatches will often be invalid objects, and may issue
errors in further analyses.







%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%
\section{Exploratory data analysis}
%%%%%%%%%%%%%%%%%%%%%
%%%%%%%%%%%%%%%%%%%%%


%%%%%%%%%%%%%%%%%%%%%
\subsection{Quantifying and testing phylogenetic signal}
%%%%%%%%%%%%%%%%%%%%%




%%%%%%%%%%%%%%%%%%%%%
\subsection{Modelling phylogenetic signal}
%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%%%
\subsection{Using multivariate analyses}
%%%%%%%%%%%%%%%%%%%%%



%%%%%%%%%%%%%%%%%%%%%
\subsection{Performing a phylogenetic Principal Component Analysis}
%%%%%%%%%%%%%%%%%%%%%




\end{document}
